### ISSUE TITLE
the holdingpen link to SNow is not clickable

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#414] opened 2023-11-06 14:45 UTC
Kirsten reports that the SNow URLs in the holdingpen are not clickable, see e.g. https://inspirehep.net/holdingpen/6306541

**Comment by PascalEgn** [comment] 2023-11-21 14:00
Closing this issue as it appears to no longer exist in new submissions (e.g. https://inspirehep.net/holdingpen/6461637).

Maybe a temporary outage was the cause for the `ticket_url` field not being populate in some workflows.

**Closed by PascalEgn** 2023-11-21 14:00 UTC
Labels: type: bug
